// Code generated by ent, DO NOT EDIT.

package character

import (
	"entgo.io/ent/dialect/sql"
	"github.com/4hoeschele/go_dnd_project/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Character {
	return predicate.Character(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Character {
	return predicate.Character(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Character {
	return predicate.Character(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Character {
	return predicate.Character(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Character {
	return predicate.Character(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Character {
	return predicate.Character(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Character {
	return predicate.Character(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Character {
	return predicate.Character(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Character {
	return predicate.Character(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Character {
	return predicate.Character(sql.FieldEQ(FieldName, v))
}

// Class applies equality check predicate on the "class" field. It's identical to ClassEQ.
func Class(v string) predicate.Character {
	return predicate.Character(sql.FieldEQ(FieldClass, v))
}

// Race applies equality check predicate on the "race" field. It's identical to RaceEQ.
func Race(v string) predicate.Character {
	return predicate.Character(sql.FieldEQ(FieldRace, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Character {
	return predicate.Character(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Character {
	return predicate.Character(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Character {
	return predicate.Character(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Character {
	return predicate.Character(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Character {
	return predicate.Character(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Character {
	return predicate.Character(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Character {
	return predicate.Character(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Character {
	return predicate.Character(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Character {
	return predicate.Character(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Character {
	return predicate.Character(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Character {
	return predicate.Character(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Character {
	return predicate.Character(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Character {
	return predicate.Character(sql.FieldContainsFold(FieldName, v))
}

// ClassEQ applies the EQ predicate on the "class" field.
func ClassEQ(v string) predicate.Character {
	return predicate.Character(sql.FieldEQ(FieldClass, v))
}

// ClassNEQ applies the NEQ predicate on the "class" field.
func ClassNEQ(v string) predicate.Character {
	return predicate.Character(sql.FieldNEQ(FieldClass, v))
}

// ClassIn applies the In predicate on the "class" field.
func ClassIn(vs ...string) predicate.Character {
	return predicate.Character(sql.FieldIn(FieldClass, vs...))
}

// ClassNotIn applies the NotIn predicate on the "class" field.
func ClassNotIn(vs ...string) predicate.Character {
	return predicate.Character(sql.FieldNotIn(FieldClass, vs...))
}

// ClassGT applies the GT predicate on the "class" field.
func ClassGT(v string) predicate.Character {
	return predicate.Character(sql.FieldGT(FieldClass, v))
}

// ClassGTE applies the GTE predicate on the "class" field.
func ClassGTE(v string) predicate.Character {
	return predicate.Character(sql.FieldGTE(FieldClass, v))
}

// ClassLT applies the LT predicate on the "class" field.
func ClassLT(v string) predicate.Character {
	return predicate.Character(sql.FieldLT(FieldClass, v))
}

// ClassLTE applies the LTE predicate on the "class" field.
func ClassLTE(v string) predicate.Character {
	return predicate.Character(sql.FieldLTE(FieldClass, v))
}

// ClassContains applies the Contains predicate on the "class" field.
func ClassContains(v string) predicate.Character {
	return predicate.Character(sql.FieldContains(FieldClass, v))
}

// ClassHasPrefix applies the HasPrefix predicate on the "class" field.
func ClassHasPrefix(v string) predicate.Character {
	return predicate.Character(sql.FieldHasPrefix(FieldClass, v))
}

// ClassHasSuffix applies the HasSuffix predicate on the "class" field.
func ClassHasSuffix(v string) predicate.Character {
	return predicate.Character(sql.FieldHasSuffix(FieldClass, v))
}

// ClassEqualFold applies the EqualFold predicate on the "class" field.
func ClassEqualFold(v string) predicate.Character {
	return predicate.Character(sql.FieldEqualFold(FieldClass, v))
}

// ClassContainsFold applies the ContainsFold predicate on the "class" field.
func ClassContainsFold(v string) predicate.Character {
	return predicate.Character(sql.FieldContainsFold(FieldClass, v))
}

// RaceEQ applies the EQ predicate on the "race" field.
func RaceEQ(v string) predicate.Character {
	return predicate.Character(sql.FieldEQ(FieldRace, v))
}

// RaceNEQ applies the NEQ predicate on the "race" field.
func RaceNEQ(v string) predicate.Character {
	return predicate.Character(sql.FieldNEQ(FieldRace, v))
}

// RaceIn applies the In predicate on the "race" field.
func RaceIn(vs ...string) predicate.Character {
	return predicate.Character(sql.FieldIn(FieldRace, vs...))
}

// RaceNotIn applies the NotIn predicate on the "race" field.
func RaceNotIn(vs ...string) predicate.Character {
	return predicate.Character(sql.FieldNotIn(FieldRace, vs...))
}

// RaceGT applies the GT predicate on the "race" field.
func RaceGT(v string) predicate.Character {
	return predicate.Character(sql.FieldGT(FieldRace, v))
}

// RaceGTE applies the GTE predicate on the "race" field.
func RaceGTE(v string) predicate.Character {
	return predicate.Character(sql.FieldGTE(FieldRace, v))
}

// RaceLT applies the LT predicate on the "race" field.
func RaceLT(v string) predicate.Character {
	return predicate.Character(sql.FieldLT(FieldRace, v))
}

// RaceLTE applies the LTE predicate on the "race" field.
func RaceLTE(v string) predicate.Character {
	return predicate.Character(sql.FieldLTE(FieldRace, v))
}

// RaceContains applies the Contains predicate on the "race" field.
func RaceContains(v string) predicate.Character {
	return predicate.Character(sql.FieldContains(FieldRace, v))
}

// RaceHasPrefix applies the HasPrefix predicate on the "race" field.
func RaceHasPrefix(v string) predicate.Character {
	return predicate.Character(sql.FieldHasPrefix(FieldRace, v))
}

// RaceHasSuffix applies the HasSuffix predicate on the "race" field.
func RaceHasSuffix(v string) predicate.Character {
	return predicate.Character(sql.FieldHasSuffix(FieldRace, v))
}

// RaceEqualFold applies the EqualFold predicate on the "race" field.
func RaceEqualFold(v string) predicate.Character {
	return predicate.Character(sql.FieldEqualFold(FieldRace, v))
}

// RaceContainsFold applies the ContainsFold predicate on the "race" field.
func RaceContainsFold(v string) predicate.Character {
	return predicate.Character(sql.FieldContainsFold(FieldRace, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Character) predicate.Character {
	return predicate.Character(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Character) predicate.Character {
	return predicate.Character(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Character) predicate.Character {
	return predicate.Character(sql.NotPredicates(p))
}
